export const FALLBACK_CHARACTERS = {
	tick: '[OK]',
	cross: '[X]',
	info: '(i)',
	warning: '!!',
	question: '(?)',
	pending: '...',
	success: '[+]',
	failure: '[-]',
	arrowUp: '^',
	arrowDown: 'v',
	arrowLeft: '<',
	arrowRight: '>',
	arrowDoubleRight: '>>',
	arrowDoubleLeft: '<<',
	arrowCurveRight: '->',
	arrowCurveLeft: '<-',
	pointer: '>',
	pointerSmall: '-',
	checkboxOn: '[X]',
	checkboxOff: '[ ]',
	radioOn: '(*)',
	radioOff: '( )',
	progressStart: '[',
	progressMid: '=',
	progressEnd: ']',
	barLeft: '[',
	barRight: ']',
	squareSmall: '[ ]',
	squareSmallFilled: '[#]',
	circle: '( )',
	circleFilled: '(O)',
	triangleUp: '/\\',
	triangleDown: '\\/',
	lozengeFilled: '<#>',
	lozenge: '<>',
	diamond: '<>',
	block: '#',
	shadeLight: '.',
	shadeMedium: '-',
	shadeDark: '=',
	boxLightHorizontal: '-',
	boxLightVertical: '|',
	boxLightTopLeft: '+',
	boxLightTopRight: '+',
	boxLightBottomLeft: '+',
	boxLightBottomRight: '+',
	boxLightTUp: '+',
	boxLightTDown: '+',
	boxLightTLeft: '+',
	boxLightTRight: '+',
	boxLightCross: '+',
	boxDoubleHorizontal: '=',
	boxDoubleVertical: '||',
	boxDoubleTopLeft: '+',
	boxDoubleTopRight: '+',
	boxDoubleBottomLeft: '+',
	boxDoubleBottomRight: '+',
	boxDoubleTUp: '+',
	boxDoubleTDown: '+',
	boxDoubleTLeft: '+',
	boxDoubleTRight: '+',
	boxDoubleCross: '+',
	boxHeavyHorizontal: '#',
	boxHeavyVertical: '#',
	boxHeavyTopLeft: '#',
	boxHeavyTopRight: '#',
	boxHeavyBottomLeft: '#',
	boxHeavyBottomRight: '#',
	boxHeavyCross: '#',
	boxRoundedTopLeft: '(',
	boxRoundedTopRight: ')',
	boxRoundedBottomLeft: '(',
	boxRoundedBottomRight: ')',
	boxRoundedHorizontal: '-',
	boxRoundedVertical: '|',
	boxRoundedHeavyTopLeft: '(',
	boxRoundedHeavyTopRight: ')',
	boxRoundedHeavyBottomLeft: '(',
	boxRoundedHeavyBottomRight: ')',
	boxRoundedHeavyHorizontal: '=',
	boxRoundedHeavyVertical: '|',
	dividerThin: '-',
	dividerThick: '=',
	dividerDouble: '=',
	dividerDashed: '- - -',
	dividerDotted: '...',
	dividerBold: '=',
	heart: '<3',
	star: '*',
	starOutline: '+',
	play: '>',
	pause: '||',
	stop: '[]',
	folder: '[dir]',
	file: '[file]',
	branch: '|--',
	fork: '+--',
	pipe: '|',
	connector: '`--',
	nodejs: '<node>',
	key: '[key]',
	gear: '[cfg]',
	clock: '[time]',
	checkmark: '[v]',
	eye: '[eye]',
	passwordMask: '*',
	ellipsis: '...',
	spinners: {
		dots: ['-', '\\', '|', '/'],
		line: ['|', '/', '-', '\\'],
		bar: [
			'[    ]',
			'[=   ]',
			'[==  ]',
			'[=== ]',
			'[====]',
			'[ ===]',
			'[  ==]',
			'[   =]',
		],
		circle: ['( )', '(•)', '(o)', '(•)'],
		bounce: ['.', 'o', 'O', 'o'],
		square: ['[]', '[=]', '[#]', '[=]'],
		clock: ['12', '3', '6', '9'],
		diagonal: ['/', '\\', '/', '\\'],
		bars: ['_', '-', '=', '-', '_'],
		wave: ['.', '..', '...', '....', '...'],
	},
} as const;
