export const UNICODE_CHARACTERS = {
	tick: '✔',
	cross: '✖',
	info: 'ℹ',
	warning: '⚠',
	question: '?',
	pending: '…',
	success: '✓',
	failure: '✗',
	arrowUp: '↑',
	arrowDown: '↓',
	arrowLeft: '←',
	arrowRight: '→',
	arrowDoubleRight: '⇒',
	arrowDoubleLeft: '⇐',
	arrowCurveRight: '↪',
	arrowCurveLeft: '↩',
	pointer: '❯',
	pointerSmall: '›',
	checkboxOn: '☑',
	checkboxOff: '☐',
	radioOn: '◉',
	radioOff: '◯',
	progressStart: '▏',
	progressMid: '▌',
	progressEnd: '▉',
	barLeft: '▐',
	barRight: '▌',
	squareSmall: '▪',
	squareSmallFilled: '■',
	circle: '○',
	circleFilled: '●',
	triangleUp: '▲',
	triangleDown: '▼',
	lozengeFilled: '◆',
	lozenge: '◇',
	diamond: '♦',
	block: '▓',
	shadeLight: '░',
	shadeMedium: '▒',
	shadeDark: '▓',
	boxLightHorizontal: '─',
	boxLightVertical: '│',
	boxLightTopLeft: '┌',
	boxLightTopRight: '┐',
	boxLightBottomLeft: '└',
	boxLightBottomRight: '┘',
	boxLightTUp: '┴',
	boxLightTDown: '┬',
	boxLightTLeft: '┤',
	boxLightTRight: '├',
	boxLightCross: '┼',
	boxDoubleHorizontal: '═',
	boxDoubleVertical: '║',
	boxDoubleTopLeft: '╔',
	boxDoubleTopRight: '╗',
	boxDoubleBottomLeft: '╚',
	boxDoubleBottomRight: '╝',
	boxDoubleTUp: '╩',
	boxDoubleTDown: '╦',
	boxDoubleTLeft: '╣',
	boxDoubleTRight: '╠',
	boxDoubleCross: '╬',
	boxHeavyHorizontal: '━',
	boxHeavyVertical: '┃',
	boxHeavyTopLeft: '┏',
	boxHeavyTopRight: '┓',
	boxHeavyBottomLeft: '┗',
	boxHeavyBottomRight: '┛',
	boxHeavyCross: '╋',
	boxRoundedTopLeft: '╭',
	boxRoundedTopRight: '╮',
	boxRoundedBottomLeft: '╰',
	boxRoundedBottomRight: '╯',
	boxRoundedHorizontal: '─',
	boxRoundedVertical: '│',
	boxRoundedHeavyTopLeft: '🭆',
	boxRoundedHeavyTopRight: '🭈',
	boxRoundedHeavyBottomLeft: '🭅',
	boxRoundedHeavyBottomRight: '🭉',
	boxRoundedHeavyHorizontal: '━',
	boxRoundedHeavyVertical: '┃',
	dividerThin: '─',
	dividerThick: '━',
	dividerDouble: '═',
	dividerDashed: '╌',
	dividerDotted: '┄',
	dividerBold: '━',
	heart: '♥',
	star: '★',
	starOutline: '☆',
	play: '▶',
	pause: '‖',
	stop: '■',
	folder: '▣',
	file: '▤',
	branch: '╰─',
	fork: '├─',
	pipe: '│',
	connector: '└─',
	nodejs: '⬢',
	key: '⭿',
	gear: '⚙',
	clock: '⧗',
	checkmark: '✓',
	eye: '👁',
	passwordMask: '•',
	ellipsis: '…',
	spinners: {
		dots: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'],
		line: ['|', '/', '─', '\\'],
		bar: ['▏', '▎', '▍', '▌', '▋', '▊', '▉', '▊', '▋', '▌', '▍', '▎'],
		circle: ['◐', '◓', '◑', '◒'],
		bounce: ['⠁', '⠂', '⠄', '⠂'],
		square: ['▖', '▘', '▝', '▗'],
		clock: ['◴', '◷', '◶', '◵'],
		diagonal: ['╱', '╲', '╱', '╲'],
		bars: ['▁', '▃', '▄', '▅', '▆', '▇', '▆', '▅', '▄', '▃'],
		wave: ['⠁', '⠂', '⠄', '⠂', '⠁', '⠈', '⠐', '⠠', '⠐', '⠈'],
	},
} as const;
